### ISSUE TITLE
fastai integration does not work

### ISSUE THREAD

**Issue by DmitriyG228** [wandb/examples#53]
Hi, fastai how not work with error:

```

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-8-d0cab4097689> in <module>
----> 1 import wandb.fastai

~/anaconda3/envs/ab/lib/python3.7/site-packages/wandb/fastai/__init__.py in <module>
      6 """
      7 
----> 8 from wandb.integration.fastai import WandbCallback
      9 
     10 __all__ = ['WandbCallback']

~/anaconda3/envs/ab/lib/python3.7/site-packages/wandb/integration/fastai/__init__.py in <module>
     38 import wandb
     39 import fastai
---> 40 from fastai.callbacks import TrackerCallback
     41 from pathlib import Path
     42 import random

ModuleNotFoundError: No module named 'fastai.callbacks'
```

They have recently released 2.0, that most probably causes problems with the callback

**Comment by DmitriyG228** [comment]
That's great, I have picked an outdated tutorial browsing links from the official site. 

The other problem with that callback is that it seems to conflict with the following custom callback:

```

class ReloadCallback(Callback):
           
    def before_epoch(self):  
        print(learn.n)
        if learn.n %6 == 0:
            t_dl,v_dl = q.get()
            print('got')
            learn.dls =  DataLoaders(t_dl,v_dl).cuda()
            print('submitted')
            
            learn.prep_dls_proccess = Process(target=prep_dls,args=(q,))
            learn.prep_dls_proccess.start() #start next
        else : pass
        learn.n+=1

```

The above callback never starts it's job in the prrecence of `WandbCallback`

**Comment by vanpelt** [comment]
@borisdayma is the original author of this callback, any ideas?

**Comment by borisdayma** [comment]
Hi @DmitriyG228 

Can you let me know where you found the original example so we make sure to tag it appropriately?
For info the best page to see fastai documentation and examples is [here](https://docs.wandb.com/library/integrations/fastai).

Also do you have a full example of the issue you have or at least the full traceback?
The place where I can think of a potential issue would be when `WandCallback` tries to get sample predictions but it may be fixed by only setting the `order` of the callbacks.

You may also be interested in using the native [Distributed DataLoaders](https://docs.fast.ai/distributed) as they have several optimizations under the hood.

**Comment by DmitriyG228** [comment]
Hi @borisdayma, the above `ReloadCallback` is my own code that is used to supply tabular data to the training loop in chunks, since the full dataset is out-of-memory. It is preparing the `dataloaders` in parallel with the training, os I don't do any distributed or parallel learning with this code.

There is no traceback since there is no error as such, but the script is waiting forever on `learn.fit_one_cycle`, obviously due to some conflict between the two callbacks.

I can prepare a reproducible example tomorrow, if it makes sense, but I probably should refactor my code the avoid conflicts with well-established software.

**Comment by borisdayma** [comment]
No worry, sometimes just by doing Ctrl + C, you can see where the script is hanging.

**Comment by borisdayma** [comment]
Also try to turn off certain features: `WandbCallback(log=None, log_preds=False, log_model=False, log_dataset=False)`

**Comment by DmitriyG228** [comment]
Hi, I have prepared a reproducible example and at has actually nothing to do with my callback, but there is some problem occurs with `multiprocessing` once `wandb` is initialized. Please run[ the following collab notebook](https://colab.research.google.com/drive/1TF7Phr-wZGSiTwqNRJgZoCbsR55l0jpf?usp=sharing)

**Comment by borisdayma** [comment]
Thanks @DmitriyG228 I confirm the bug.
On a side note, I wonder if you could directly customize Dataloaders getters to avoid your OOM problem.

I updated a bit your notebook so that we can easily reproduce the issue: [colab](https://colab.research.google.com/drive/1wi1da3g0jBL-CJfJxuoQHLhqpkt-YJ0v?usp=sharing)

I'm wondering if there's a conflict with the monitoring of computer resources. We'll investigate.
Thanks again for reporting it.

**Comment by scottire** [comment]
@borisdayma Can this be closed?

**Comment by borisdayma** [comment]
Yes, I think so
