### ISSUE TITLE
pytorch lightning multi gpu wandb sweep example

### ISSUE THREAD

**Issue by tobiascz** [wandb/examples#84]
A pytorch lightning multi gpu (ddp) sweep example would be a great addition to the resources.

**Comment by charlesfrye** [comment]
Thanks for the suggestion @tobiascz!

To be clear: you're suggesting an example with multiple single-node/multi-GPU agents all contributing runs to a sweep? We have relatively limited examples with multi-GPU training, because our examples are mostly backed by Colab, which only offers a single GPU.

FYI: If you're comfortable only submitting metrics from the rank0 process, this shouldn't be any harder, on the `wandb` side, than running a sweep with single-node/single-GPU agents. There's no need for `wandb` to know about the other processes driving the other GPUs. That approach is [Method 1 here](https://docs.wandb.ai/guides/track/advanced/distributed-training). That said, I'm not super familiar with Lightning's approach for DDP, so there might be a bit more work/subtlety involved relative to vanilla PyTorch.

**Comment by tobiascz** [comment]
Hey @charlesfrye,

Yes exactly - sinlge-node/multi-GPU run using sweeps and pytorch lightning. Your right, its currently not possible to have multiple gpus in colab unfortunetly,

The issue is with pytorch lightning that it only logs on rank0. This is however a problem for multi-gpu training as the wandb.config is only available on rank0 as well. So rank1,2,3... don't have any access to the sweep parameter. So i was wondering if there is any workaround - I already created an issue at [lightning-kitti](https://github.com/borisdayma/lightning-kitti/issues/3 ).

**Comment by charlesfrye** [comment]
That is a tricky one.

If you're using [`wandb agent`](https://docs.wandb.ai/ref/cli/wandb-agent), the CLI interface to Sweeps, you can access the config information [via the command line](https://docs.wandb.ai/guides/sweeps/configuration#command). I don't think there's a way to avoid the dependence on the `wandb.config` for [`wandb.agent`](https://docs.wandb.ai/ref/python/agent), the Python interface to Sweeps. @dannygoldstein chime in if you've got any better ideas.

**Comment by tobiascz** [comment]
Thanks for the suggestion with the command line. I tried it with a sample
```
    print(len(sys.argv))
    print(str(sys.argv))
```

unfortunately here the sweep parameters do not show up here. Is there another way to access those?

**Comment by dannygoldstein** [comment]
@tobiascz 

This will get much easier in 0.13.0 when we rework the entire way of dealing with multiprocessing environments in the client. It should be straightforward in that release

**Comment by tobiascz** [comment]
> @tobiascz
> 
> This will get much easier in 0.13.0 when we rework the entire way of dealing with multiprocessing environments in the client. It should be straightforward in that release

Can't wait!
